version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${SERVER_PORT}:1935
    tty: true
    restart: always
